dist: bionic
osx_image: xcode10.2
sudo: required
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "node"
cache: npm
script:
  - npm run dist
addons:
  homebrew:
    packages:
    - openssl@1.1
    update: true
  apt:
    packages:
    - libssl-dev
    update: true
